Issue 610
pion/webrtc pull request #1437
Opened 2020-09-21 14:05 UTC by obasajujoshua31

implemented getstats api for rpccodec

#### Description

#### Reference issue
https://github.com/pion/webrtc/issues/610
Fixes #...

2020-09-21 14:39 UTC, Sean-Der commented on stats_go.go
> +func (r StatsReport) GetCodecStats(c *RTPCodec) (CodecStats, bool) {
`GetMediaStats` is probably better. I need to look at `pc-stats` and see if a better name comes out.

2020-09-21 14:40 UTC, Sean-Der commented
Look pretty good @obasajujoshua31 I am still reviewing but would you mind changing the commit message to something like this.

```
Add GetMediaStats to StatsReport

Add an API to get basic stats around media. 

Relates to #610 
```

If I am reading `git log` the current commit message makes it really hard to understand what is going on. thanks!

2020-09-22 03:05 UTC, tarrencev requested changes

2020-09-22 03:05 UTC, tarrencev commented on mediaengine.go
> +		PayloadType: uint32(r.PayloadType),
This type can be modified to `uint8` in the `CodecStats` struct definition

2020-09-22 03:05 UTC, tarrencev commented on mediaengine.go
> +		Channels:    uint32(r.Channels),
This is defined as a `unsigned short` in the spec but we can use `uint8` in go. Please update this in the `CodecStats` struct too.

2020-09-22 03:05 UTC, tarrencev commented on mediaengine.go
> +		CodecType:   codecType,
> "encode" or "decode", depending on whether this object represents a media format that the implementation is prepared to encode or decode.

@Sean-Der does this make sense in the context of pion?

2020-09-22 03:05 UTC, tarrencev commented on mediaengine.go
> +func (r *RTPCodec) collectStats(collector *statsReportCollector, codecType CodecType) {
`codecType` shouldn't be passed in here

2020-09-22 12:41 UTC, tarrencev commented on peerconnection.go
> +		for _, sender := range pc.GetSenders() {
You can use `GetTransceivers` to get both senders and receivers

2020-09-22 12:42 UTC, tarrencev commented on peerconnection.go
> +	if pc.api.mediaEngine != nil {
I dont think this can be `nil`

2020-09-22 13:06 UTC, tarrencev commented on peerconnection.go
> +		for _, sender := range pc.GetSenders() {
Actually, I dont think this should be derived from the transceivers. It should just be generated based on the current `MediaEngine`. You can define a method `MediaEngine.collectStats` that aggregates codec stats then is called here with `pc.api.mediaEngine.collectStats(...)`

2020-09-22 18:05 UTC, merged