Add reference to NLnet sponsoring
pion/webrtc pull request #2191
Opened 2022-04-23 12:16 UTC by mengelbart

NLnet sponsors work on congestion control in Pion.

2022-04-29 18:15 UTC, kevmo314 approved these changes

2022-05-08 10:59 UTC, daenney requested changes
The current wording suggests all of the work on pion/webrtc was funded by NLnet, which is not the case to the best of my knowledge.

I would change the messaging in the Sponsoring section to be scoped to the work NLnet funded, the congestion control.

2022-07-15 14:37 UTC, mengelbart commented
Sorry I didn't get back to this earlier @daenney ! I changed the wording to be more specific about what was funded.

2022-07-16 09:15 UTC, daenney approved these changes

2022-07-16 09:16 UTC, merged